# Generated by GPT

class Matrix4x4:
    def __init__(self, elements=None):
        if elements is None:
            self.elements = [
                [1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, 1]
            ]
        else:
            self.elements = elements

    @staticmethod
    def identity():
        return Matrix4x4()

    def __mul__(self, other):
        result = [
            [0, 0, 0, 0],
            [0, 0, 0, 0],
            [0, 0, 0, 0],
            [0, 0, 0, 0]
        ]
        for i in range(4):
            for j in range(4):
                for k in range(4):
                    result[i][j] += self.elements[i][k] * other.elements[k][j]
        return Matrix4x4(result)

    def translate(self, x, y, z):
        translation_matrix = Matrix4x4([
            [1, 0, 0, x],
            [0, 1, 0, y],
            [0, 0, 1, z],
            [0, 0, 0, 1]
        ])
        return self * translation_matrix

    def __str__(self):
        return f"Matrix4x4(elements={self.elements})"

    def __repr__(self):
        return self.__str__()
